//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqToolkit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LinqToolkit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected MethodCallExpression: {0}.
        /// </summary>
        internal static string CreateQueryInvalidOperationFormat {
            get {
                return ResourceManager.GetString("CreateQueryInvalidOperationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported query operator detected: {0}.
        /// </summary>
        internal static string CreateQueryNotSupportedFormat {
            get {
                return ResourceManager.GetString("CreateQueryNotSupportedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property marked with IgnoreAttribute: {0}.
        /// </summary>
        internal static string GetPropertyNameIgnoreAttributeFormat {
            get {
                return ResourceManager.GetString("GetPropertyNameIgnoreAttributeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declaring type is not assignable from original: {0}.
        /// </summary>
        internal static string GetPropertyNameNotAssignableFormat {
            get {
                return ResourceManager.GetString("GetPropertyNameNotAssignableFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A filtering expression should contain an entity member as the left operand: {0}.
        /// </summary>
        internal static string ParseConditionExpressionNotSupportedFormat {
            get {
                return ResourceManager.GetString("ParseConditionExpressionNotSupportedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported query expression detected: {0}.
        /// </summary>
        internal static string ParseQueryNotSupportedFormat {
            get {
                return ResourceManager.GetString("ParseQueryNotSupportedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unary expression should contain an entity member as the operand: {0}.
        /// </summary>
        internal static string ParseUnaryExpressionNotSupportedFormat {
            get {
                return ResourceManager.GetString("ParseUnaryExpressionNotSupportedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item is not found..
        /// </summary>
        internal static string TableDeleteItemNotFound {
            get {
                return ResourceManager.GetString("TableDeleteItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter item is null..
        /// </summary>
        internal static string TableDeleteItemNull {
            get {
                return ResourceManager.GetString("TableDeleteItemNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item was already deleted..
        /// </summary>
        internal static string TableInsertItemAlreadyDeleted {
            get {
                return ResourceManager.GetString("TableInsertItemAlreadyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item is already exists..
        /// </summary>
        internal static string TableInsertItemAlreadyExists {
            get {
                return ResourceManager.GetString("TableInsertItemAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter item is null..
        /// </summary>
        internal static string TableInsertItemNull {
            get {
                return ResourceManager.GetString("TableInsertItemNull", resourceCulture);
            }
        }
    }
}
